#!/bin/bash

app=odoo

# Remove Docker container and systemd service but keep the pulled image and Docker
	sudo yunohost service remove container-$app
	sudo rm /etc/systemd/system/container-$app.service

	sudo docker stop $app
	sudo docker rm $app
	sudo docker stop $app-db
	sudo docker rm $app-db

# Remove NGINX conf
	domain=$(sudo yunohost app setting $app domain)
	sudo rm /etc/nginx/conf.d/$domain.d/$app.conf

# Reload
	sudo service nginx reload
	sudo yunohost app ssowatconf 