#!/bin/bash

app=odoo

# The parameter $1 is the backup directory location which will be compressed afterward
	backup_dir=$1/apps/container-$app
	mkdir -p $backup_dir

# Backup container's volumes
	echo 'Restoring Odoo'
	sudo docker stop $app
	sudo docker stop $app-db
	docker run --rm --volumes-from $app -v $backup_dir:/backup odoo tar xvf /backup/container-$app.tar
	docker run --rm --volumes-from $app-db -v $backup_dir:/backup postgres tar xvf /backup/container-$app-db.tar

# Restore the systemd service and nginx
	sudo cp -a $backup_dir/container-$app.service /etc/systemd/system/container-$app.service
	sudo chmod 777 /etc/systemd/system/container-$app.service
	sudo systemctl enable /etc/systemd/system/container-$app.service
	sudo systemctl daemon-reload
	
	#Nginx TBD

# Restore YunoHost parameters
	sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app