#!/bin/bash

app=dockerodoo

# The parameter $1 is the backup directory location which will be compressed afterward
	backup_dir=$1/apps/container-$app
	mkdir -p $backup_dir

# Backup container's volumes
	echo 'Restoring Odoo'
	sudo docker stop odoo
	sudo docker stop odoodb
	docker run --rm --volumes-from odoo -v $backup_dir:/backup odoo tar xvf /backup/container-odoo.tar
	docker run --rm --volumes-from odoodb -v $backup_dir:/backup postgres tar xvf /backup/container-odoodb.tar

# Restore the systemd service and nginx
	sudo cp -a $backup_dir/container-$app.service /etc/systemd/system/container-$app.service
	sudo chmod 777 /etc/systemd/system/container-$app.service
	sudo systemctl enable /etc/systemd/system/container-$app.service
	sudo systemctl daemon-reload
	
	#Nginx TBD

# Restore YunoHost parameters
	sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app